blockList = [
  'acl.getCurrentPermissions',
  'audit.checkIntegrity',
  'audit.getRecords',
  'backupNg.getAllJobs',
  'backupNg.getAllLogs',
  'group.getAll',
  'host.stats',
  'ipPool.getAll',
  'job.getAll',
  'log.get',
  'metadataBackup.getAllJobs',
  'plugin.get',
  'pool.listMissingPatches',
  'resourceSet.getAll',
  'schedule.getAll',
  'server.getAll',
  'session.getUser',
  'sr.stats',
  'system.getMethodsInfo',
  'system.getServerTimezone',
  'system.getServerVersion',
  'system.listMethods',
  'user.getAll',
  'vm.stats',
  'xo.getAllObjects',
]
